const BACKEND_URL = 'http://localhost:5000';
const FRONTEND_URL = 'http://localhost:3000';

async function postJSON(url, data, token) {
  const headers = { 'Content-Type': 'application/json' };
  if (token) headers['Authorization'] = `Bearer ${token}`;
  const res = await fetch(url, {
    method: 'POST',
    headers,
    body: JSON.stringify(data),
  });
  return { status: res.status, data: await res.json() };
}

async function getJSON(url, token) {
  const headers = { 'Content-Type': 'application/json' };
  if (token) headers['Authorization'] = `Bearer ${token}`;
  const res = await fetch(url, {
    method: 'GET',
    headers,
  });
  return { status: res.status, data: await res.json() };
}

async function deleteItem(url, token) {
  const headers = { 'Content-Type': 'application/json' };
  if (token) headers['Authorization'] = `Bearer ${token}`;
  const res = await fetch(url, {
    method: 'DELETE',
    headers,
  });
  return { status: res.status, data: await res.json() };
}

async function runTest() {
  console.log('═══════════════════════════════════════════════');
  console.log('🚀 TESTING DAILY FOCUS AI SIGNATURE FEATURE');
  console.log('═══════════════════════════════════════════════\n');

  // 1. AUTHENTICATE
  console.log('--- Step 1: Authentication ---');
  const login = await postJSON(`${BACKEND_URL}/api/auth/login`, {
    email: 'sarah@apextech.io',
    password: 'Password123!',
  });
  if (!login.data.success) throw new Error('Sarah login failed: ' + JSON.stringify(login.data));
  const token = login.data.accessToken;
  const user = login.data.user;
  console.log(`✓ Authenticated as: ${user.fullName} (${user._id})`);

  // 2. SEED WORKLOAD ITEMS
  console.log('\n--- Step 2: Seeding Workload (Overdue Task, Due Today Task, Meeting) ---');
  const now = new Date();
  const twoDaysAgo = new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000);
  const endOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 23, 59, 0);
  const meetingTime = new Date(now.getTime() + 2 * 60 * 60 * 1000);

  // Overdue Task
  const t1 = await postJSON(
    `${BACKEND_URL}/api/tasks`,
    {
      title: 'Fix Critical Security Patch in Auth Token Rotation',
      description: 'Overdue high-impact task that requires immediate action',
      priority: 'urgent',
      status: 'todo',
      dueDate: twoDaysAgo.toISOString(),
      assigneeId: user._id,
    },
    token
  );
  if (t1.status !== 201) throw new Error('Failed to create overdue task: ' + JSON.stringify(t1.data));
  const taskId1 = t1.data.task?._id || t1.data.data?._id;
  console.log(`✓ Created Overdue Task: "${t1.data.task?.title || t1.data.data?.title}" (ID: ${taskId1})`);

  // Due Today Task
  const t2 = await postJSON(
    `${BACKEND_URL}/api/tasks`,
    {
      title: 'Submit Q3 Sprint Deliverables Review',
      description: 'Task expiring by the end of today',
      priority: 'high',
      status: 'in_progress',
      dueDate: endOfToday.toISOString(),
      assigneeId: user._id,
    },
    token
  );
  if (t2.status !== 201) throw new Error('Failed to create due today task: ' + JSON.stringify(t2.data));
  const taskId2 = t2.data.task?._id || t2.data.data?._id;
  console.log(`✓ Created Due Today Task: "${t2.data.task?.title || t2.data.data?.title}" (ID: ${taskId2})`);

  // Meeting Today
  const m1 = await postJSON(
    `${BACKEND_URL}/api/meetings`,
    {
      title: 'Architecture Review & AI Prioritization Sync',
      description: 'Scheduled sync for team leads',
      scheduledAt: meetingTime.toISOString(),
    },
    token
  );
  if (m1.status !== 201) throw new Error('Failed to create meeting: ' + JSON.stringify(m1.data));
  const meeting = m1.data.meeting || m1.data.data;
  console.log(`✓ Created Today Meeting: "${meeting.title}" (Link: ${meeting.meetingLink})`);

  // 3. FORCE REFRESH DAILY FOCUS
  console.log('\n--- Step 3: Fetching /api/daily-focus?refresh=true ---');
  const focusRes = await getJSON(`${BACKEND_URL}/api/daily-focus?refresh=true`, token);
  if (!focusRes.data.success) throw new Error('Failed to fetch daily focus: ' + JSON.stringify(focusRes.data));

  const focusData = focusRes.data.data;
  console.log(`✓ Daily Focus Generated by: [${focusData.generatedBy.toUpperCase()}]`);
  console.log(`✓ Summary: "${focusData.summary}"`);
  console.log(`✓ Total Items: ${focusData.focusItems.length}`);
  console.log(`✓ Total Urgent Count: ${focusData.totalUrgentCount}`);

  if (focusData.focusItems.length === 0) {
    throw new Error('Expected focusItems to have items, got 0');
  }

  console.log('\nRanked Focus Items:');
  focusData.focusItems.forEach((item, idx) => {
    console.log(`  ${idx + 1}. [${item.type.toUpperCase()}] "${item.title}"`);
    console.log(`     Reason:   ${item.reason}`);
    console.log(`     Priority: ${item.priority} | Badge: ${item.badge} | Link: ${item.link}`);
  });

  // Verify rank 1 is urgent / overdue
  const topItem = focusData.focusItems[0];
  console.log(`\n✓ Top Ranked Item is: "${topItem.title}" with priority [${topItem.priority}]`);

  // 4. VERIFY CACHING
  console.log('\n--- Step 4: Testing Cache Hit (Subsequent Fetch) ---');
  const cachedRes = await getJSON(`${BACKEND_URL}/api/daily-focus`, token);
  if (!cachedRes.data.success) throw new Error('Failed to fetch cached daily focus');
  console.log(`✓ Cached flag received: ${cachedRes.data.cached} (expected: true)`);
  if (!cachedRes.data.cached) throw new Error('Cache miss when cache hit was expected!');

  // 5. VERIFY FRONTEND PAGES
  console.log('\n--- Step 5: Testing Frontend Pages ---');
  const dashRes = await fetch(`${FRONTEND_URL}/dashboard`);
  console.log(`✓ Frontend /dashboard HTTP status: ${dashRes.status}`);

  const dailyFocusPageRes = await fetch(`${FRONTEND_URL}/daily-focus`);
  console.log(`✓ Frontend /daily-focus HTTP status: ${dailyFocusPageRes.status}`);

  if (dashRes.status !== 200 || dailyFocusPageRes.status !== 200) {
    throw new Error('Frontend route returned non-200 status');
  }

  // 6. CLEAN UP TEST DATA
  console.log('\n--- Step 6: Cleaning Up Test Workload ---');
  if (taskId1) await deleteItem(`${BACKEND_URL}/api/tasks/${taskId1}`, token);
  if (taskId2) await deleteItem(`${BACKEND_URL}/api/tasks/${taskId2}`, token);
  if (meeting?.meetingLink) {
    await postJSON(`${BACKEND_URL}/api/meetings/${meeting.meetingLink}/end`, {}, token);
  }
  console.log('✓ Test tasks and meeting cleaned up successfully');

  console.log('\n======================================================');
  console.log('🎉 ALL DAILY FOCUS AI SIGNATURE FEATURE TESTS PASSED!');
  console.log('======================================================\n');
}

runTest().catch((err) => {
  console.error('\n❌ TEST FAILED:', err);
  process.exit(1);
});
